log:
  level: 5

replicaCount: 1
certDuration: 87600h
nameOverrider: ""

image:
  gritmanager:
    registry: kaito.sh
    repository: grit-manager
    tag: 0.0.1
    pullSecrets: []
  gritagent:
    registry: kaito.sh
    repository: grit-agent
    tag: 0.0.1

ports:
  metrics: 10351
  webhook: 10350
  healthProbe: 10352

resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 256Mi
  