---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grit-agent-clusterrole
rules:
- apiGroups:
  - kaito.sh
  resources:
  - checkpoints
  verbs:
  - get
- apiGroups:
  - kaito.sh
  resources:
  - checkpoints/status
  verbs:
  - update
