apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cr-demo-pvc9
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 256Gi
