apiVersion: v1
kind: ConfigMap
metadata:
  name: grit-agent-config
  namespace: {{ .Release.Namespace }}
data:
  host-path: "/var/lib/grit-agent"
  grit-agent.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{.jobName}}
      namespace: {{.namespace}}
      labels:
        grit.dev/helper: grit-agent
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          nodeName: {{.nodeName}}
          tolerations:
          - operator: "Exists"
          containers:
          - name: grit-agent
            image: kaito.sh/grit-agent:latest
            command: ["/usr/local/bin/grit-agent"]
            imagePullPolicy: IfNotPresent