apiVersion: v1
kind: ConfigMap
metadata:
  name: grit-agent-config
  namespace: {{ .Release.Namespace }}
data:
  host-path: {{ .Values.hostPath }}
  grit-agent-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{`{{`}} .jobName {{`}}`}}
      namespace: {{`{{`}} .namespace {{`}}`}}
      labels:
        grit.dev/helper: grit-agent
    spec:
      backoffLimit: 3
      template:
        spec:
          hostNetwork: true
          restartPolicy: Never
          volumes:
          - name: containerd-sock
            hostPath:
              path: /run/containerd/containerd.sock
              type: Socket
          - name: pod-logs
            hostPath:
              path: /var/log/pods
              type: Directory
          nodeName: {{`{{`}} .nodeName {{`}}`}}
          tolerations:
          - operator: "Exists"
          containers:
          - name: grit-agent
            image: {{ .Values.image.gritagent.registry }}/{{ .Values.image.gritagent.repository }}:{{ .Values.image.gritagent.tag | default .Chart.AppVersion }}
            command: ["/grit-agent"]
            args: ["--v=5"]
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
            - name: pod-logs
              mountPath: /var/log/pods
