apiVersion: v1
kind: ConfigMap
metadata:
  name: grit-agent-config
  namespace: {{ .Release.Namespace }}
data:
  host-path: "/var/lib/grit-agent"
  grit-agent-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{`{{`}} .jobName {{`}}`}}
      namespace: {{`{{`}} .namespace {{`}}`}}
      labels:
        grit.dev/helper: grit-agent
    spec:
      backoffLimit: 3
      template:
        spec:
          hostNetwork: true
          restartPolicy: Never
          volumes:
          - name: containerd-sock
            hostPath:
              path: /run/containerd/containerd.sock
              type: Socket
          nodeName: {{`{{`}} .nodeName {{`}}`}}
          tolerations:
          - operator: "Exists"
          containers:
          - name: grit-agent
            image: {{ .Values.image.gritagent.registry }}/{{ .Values.image.gritagent.repository }}:{{ .Values.image.gritagent.tag | default .Chart.AppVersion }}
            command: ["/bin/sh", "-c", "sleep infinity"]
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: containerd-sock
              mountPath: /run/containered/containerd.sock