apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kaito-nvidia-device-plugin-daemonset-cdi
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.azure.com/cluster
                    operator: Exists
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      tolerations:
        # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
        # This, along with the annotation above marks this pod as a critical add-on.
        - key: CriticalAddonsOnly
          operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: "sku"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      priorityClassName: "system-node-critical"
      containers:
        - image: mcr.microsoft.com/oss/v2/nvidia/k8s-device-plugin:v0.17.0
          imagePullPolicy: IfNotPresent
          name: nvidia-device-plugin-ctr
          env:
            - name: FAIL_ON_INIT_ERROR
              value: "false"
            - name: PASS_DEVICE_SPECS
              value: "true"
            - name: DEVICE_LIST_STRATEGY
              value: cdi-cri
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - mountPath: /var/run/cdi
              name: cdi-root
            - mountPath: /driver-root
              name: driver-root
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
          name: cdi-root
        - hostPath:
            path: /
            type: ""
          name: driver-root