name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  GO_VERSION: '1.22.3'

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Check spelling with custom config file
        uses: crate-ci/typos@v1.29.9
        with:
          config: ./.github/typos.toml

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --base . --verbose --no-progress './**/*.md'
          fail: false

      - name: Verify Mod
        run: make verify-mod

      - name: Verify Manifests
        run: make verify-manifests

